// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-2:4a5d71fc-923f-442f-b594-b84f12a29bc8',
    'aws_cognito_region': 'us-east-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'photoclient-hosting-mobilehub-1689714935',
    'aws_content_delivery_bucket_region': 'us-east-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd302poedl4ofxn.cloudfront.net',
    'aws_mobile_analytics_app_id': '901b65cf595141fa93874f81910b58e1',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'b40e1b6d-673b-43d8-ba05-2b8d949d3ded',
    'aws_project_name': 'photo-client-2018-04-07-12-04-33',
    'aws_project_region': 'us-east-2',
    'aws_resource_name_prefix': 'photoclient-mobilehub-1689714935',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'photoclient-userfiles-mobilehub-1689714935',
    'aws_user_files_s3_bucket_region': 'us-east-2',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-2_r4TgictrP',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '1uncm71e2mfqusoko1qbs6jf45',
    'aws_appsync_apiId': 'mhcwshjmwzb63kh2btovseqxqa',
    'aws_appsync_name': 'photo-client-2018-04-07-12-04-33',
    'aws_appsync_graphqlEndpoint': 'https://uhk2ylk2dbcmhln37sxm3qbj3y.appsync-api.us-east-2.amazonaws.com/graphql',
    'aws_appsync_region': 'us-east-2',
    'aws_appsync_authenticationType': 'AWS_IAM',
    'aws_appsync_AppSyncConsoleUrl': 'https://console.aws.amazon.com/appsync/home?region=us-east-2#/mhcwshjmwzb63kh2btovseqxqa/v1/home',
    'aws_appsync_apiKey': 'da2-lhj2nogkeber7evgtvnxkvdfry',
    'aws_appsync_lastSyncToDevTime': '2018-04-07-18-55-57',
}

export default awsmobile;
